X1 = float(input("First number position: "))
fX1 = float(input("First number: "))
X2 = float(input("Second number position: "))
fX2 = float(input("Second number: "))
X = float(input("Interpolated position: "))
out = fX1+(fX2-fX1)*(X-X1)/(X2-X1)
print(out)
input()